# Generated by Django 3.2.12 on 2023-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='off_price',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
