# Generated by Django 3.2.12 on 2023-10-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_place_off_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='off_price',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
